package com.greendaodemo.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.greendao.bean.Master;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MASTER".
*/
public class MasterDao extends AbstractDao<Master, Long> {

    public static final String TABLENAME = "MASTER";

    /**
     * Properties of entity Master.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property MId = new Property(0, Long.class, "mId", true, "_id");
        public final static Property MUserName = new Property(1, String.class, "mUserName", false, "M_USER_NAME");
        public final static Property MSex = new Property(2, String.class, "mSex", false, "M_SEX");
    }


    public MasterDao(DaoConfig config) {
        super(config);
    }
    
    public MasterDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MASTER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: mId
                "\"M_USER_NAME\" TEXT," + // 1: mUserName
                "\"M_SEX\" TEXT);"); // 2: mSex
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MASTER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Master entity) {
        stmt.clearBindings();
 
        Long mId = entity.getMId();
        if (mId != null) {
            stmt.bindLong(1, mId);
        }
 
        String mUserName = entity.getMUserName();
        if (mUserName != null) {
            stmt.bindString(2, mUserName);
        }
 
        String mSex = entity.getMSex();
        if (mSex != null) {
            stmt.bindString(3, mSex);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Master entity) {
        stmt.clearBindings();
 
        Long mId = entity.getMId();
        if (mId != null) {
            stmt.bindLong(1, mId);
        }
 
        String mUserName = entity.getMUserName();
        if (mUserName != null) {
            stmt.bindString(2, mUserName);
        }
 
        String mSex = entity.getMSex();
        if (mSex != null) {
            stmt.bindString(3, mSex);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Master readEntity(Cursor cursor, int offset) {
        Master entity = new Master( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // mId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // mUserName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // mSex
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Master entity, int offset) {
        entity.setMId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMUserName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMSex(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Master entity, long rowId) {
        entity.setMId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Master entity) {
        if(entity != null) {
            return entity.getMId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Master entity) {
        return entity.getMId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
